name: jlink

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Make JRE
      run: jlink --module-path $JAVA_HOME/jmods/ --add-modules java.desktop --compress=2 --strip-debug --output JRE_for_lizzie
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: JRE_for_lizzie
        path: JRE_for_lizzie
